spring:
  config:
    import: configserver:https://ms-innovatube-config-server-uxqd.onrender.com/
  application:
    name: innovatube-jwt
    
server:
  port: 8092

eureka:
  instance:
    prefer-ip-address: true